### ISSUE TITLE
No such file or directory: '..\\data\\paris_zipped\\paris\\paris_120310\\pompidou_2_bad.txt'

### ISSUE THREAD

**Issue by zuixiaosanlang** [NHGJem/tensorflow2-NetVLAD#2]
![image](https://user-images.githubusercontent.com/20105627/145211976-4f2922c0-2e8f-4e5e-99c9-ba6d98ed108a.png)

not find about *bad.txt

**Comment by NHGJem** [comment]
The _bad text files can be downloaded from [this repository](https://github.com/keshik6/deep-image-retrieval#google-drive-link) as mentioned in the Data section.
